<?php
/**
 * @file
 *   szantog_offers.module
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

/**
 * Implements hook_views_api().
 */
function szantog_offers_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'szantog_offers') . '/views',
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function szantog_offers_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Helper function to get coordinates from a wkt text.
 *
 * @param $wkt
 */
function szantog_offers_parse_wkt($wkt) {
  $wkt = str_replace('POINT ', '', $wkt);
  $wkt = str_replace('(', '', $wkt);
  $wkt = str_replace(')', '', $wkt);
  return str_replace(' ', ', ', $wkt);
}

/**
 * This is a sample function to set openlayers map default center to a stored
 * value. This needs, because openlayers defaults are constant, the geofield
 * module doesn't pass own variable.
 *
 * @param $vars
 */
function SAMPLE_preprocess_openlayers_map(&$vars) {
  $map = &$vars['map'];

  if ($map['map_name'] = 'tips_node_map' && $node = menu_get_object()) {
    $center = szantog_offers_parse_wkt($node->field_map['und'][0]['wkt']);
    $map['center']['initial']['centerpoint'] = $center;
  }

  $js = array('openlayers' => array('maps' => array($map['id'] => $map)));
  drupal_add_js($js, 'setting');
  dsm(get_defined_vars());
}
