<?php
/**
 * @file
 *   szantog_offers.module
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

/**
 * Implements hook_views_api().
 */
function szantog_offers_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'szantog_offers') . '/views',
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function szantog_offers_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return 'plugins/' . $plugin;
  }
}
