<?php
/**
 * @file
 *   szantog_offers.module
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

/**
 * Implements hook_views_api().
 */
function szantog_offers_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'szantog_offers') . '/views',
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function szantog_offers_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Helper function to get coordinates from a wkt text.
 *
 * @param $wkt
 */
function szantog_offers_parse_wkt($wkt) {
  $wkt = str_replace('POINT ', '', $wkt);
  $wkt = str_replace('(', '', $wkt);
  $wkt = str_replace(')', '', $wkt);
  return str_replace(' ', ', ', $wkt);
}

function szantog_offers_widget_refresh($form, $form_state) {
  // The target element is one element below the triggering country selector.
  $array_parents = $form_state['triggering_element']['#array_parents'];
  $wrapper_id = $form_state['triggering_element']['#ajax']['wrapper'];
  array_pop($array_parents);

  // Iterate over the form parents to find the element.
  $element = $form;
  foreach ($array_parents as $name) {
    $element = &$element[$name];
    if (!empty($element['#addressfield'])) {
      break;
    }
  }
  // Add replace element as default AJAX command.
  $commands = array();
  $commands[] = ajax_command_replace(NULL, drupal_render($element));
  $commands[] = ajax_command_invoke(NULL, 'Drupal.attachBehaviors');

  drupal_alter('addressfield_standard_widget_refresh', $commands, $form, $form_state);

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * This is a sample function to set openlayers map default center to a stored
 * value. This needs, because openlayers defaults are constant, the geofield
 * module doesn't pass own variable.
 *
 * @param $vars
 */
function SAMPLE_preprocess_openlayers_map(&$vars) {
  $map = &$vars['map'];

  if ($map['map_name'] = 'tips_node_map' && $node = menu_get_object()) {
    $center = szantog_offers_parse_wkt($node->field_map['und'][0]['wkt']);
    $map['center']['initial']['centerpoint'] = $center;
  }

  $js = array('openlayers' => array('maps' => array($map['id'] => $map)));
  drupal_add_js($js, 'setting');
}

/**
 * Implements hook_metatag_info_alter().
 */
function szantog_offers_metatag_info() {
  $info['tags']['fb:app_id'] = array(
    'label' => t('Open Graph Facebook App id.'),
    'description' => t('The id of facebook application connected to the site.'),
    'class' => 'DrupalTextMetaTag',
    'group' => 'open-graph',
    'element' => array(
      '#theme' => 'metatag_opengraph',
    ),
  );
  return $info;
}
